### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by samdolt** [bcornwellmott/octoerp#1]
Hello,

I have installed octoerp using:

```bash
bench get-app octoerp https://github.com/bcornwellmott/octoerp.git
bench install-app octoerp
```

Then I have added the script from the readme in custom script

- But I doesn't see any octoerp app in the website.
- When I click in the octopart lockup button, the page reload but price are not updated

I'm a newbie with ERPnext, so I didn't know what could be wrong

**Comment by bcornwellmott** [comment]
I think I may have fixed the issues. Please try updating.

I've added more information to the readme. You need to go to the new Octo-ERP Settings form, where you can plug in your API key (must request from Octopart). You also need to fill in the Octopart Seller Name field in each supplier.

Finally, you **need** to make sure the manufacturers part number is set for each item in your supplier quotation.

I'm going to close this for now, but if it's not working for you, please let me know.
